from backend.models.destination import Destination
from backend.models.tourist_place import TouristPlace
from backend.models.verified_service import VerifiedService
from backend.database.db import db
import json

def seed_initial_data():
    """Seed comprehensive destinations, tourist places, and verified emergency services"""
    if Destination.query.first() and TouristPlace.query.first():
        return

    # 1. Clean existing tables if partial
    db.session.query(TouristPlace).delete()
    db.session.query(Destination).delete()
    db.session.query(VerifiedService).delete()
    db.session.commit()

    # 2. Destinations Dataset
    destinations_data = [
        {
            'id': 'hyderabad',
            'name': 'Hyderabad',
            'type': 'Metropolitan & Heritage Capital',
            'state': 'Telangana',
            'state_id': 'telangana',
            'region': 'South India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Food & Culture', 'Nature']),
            'image': 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?auto=format&fit=crop&w=800&q=80',
            'description': 'City of Pearls and royal Nizami heritage blending medieval fortresses, iconic minarets, and high-tech urban brilliance.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 4,
            'latitude': 17.3850,
            'longitude': 78.4867,
        },
        {
            'id': 'visakhapatnam',
            'name': 'Visakhapatnam',
            'type': 'Coastal Port City',
            'state': 'Andhra Pradesh',
            'state_id': 'andhra-pradesh',
            'region': 'South India',
            'country': 'India',
            'categories': json.dumps(['Beaches', 'Heritage', 'Nature', 'Spiritual']),
            'image': 'https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=800&q=80',
            'description': 'Coastal jewel nestled between the Eastern Ghats and Bay of Bengal with submarine museums, hilltop ropeways, and beach drives.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 4,
            'latitude': 17.6868,
            'longitude': 83.2185,
        },
        {
            'id': 'delhi',
            'name': 'Delhi',
            'type': 'National Capital Territory',
            'state': 'Delhi',
            'state_id': 'delhi',
            'region': 'North India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Food & Culture', 'Spiritual']),
            'image': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
            'description': "India's historic capital city showcasing centuries of Mughal grandeur, monumental boulevards, and vibrant bazaars.",
            'safety_level': 'MODERATE',
            'best_season': 'October to March',
            'place_count': 4,
            'latitude': 28.6139,
            'longitude': 77.2090,
        },
        {
            'id': 'jaipur',
            'name': 'Jaipur',
            'type': 'Royal Capital & UNESCO World Heritage',
            'state': 'Rajasthan',
            'state_id': 'rajasthan',
            'region': 'North India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Art & Architecture', 'Food & Culture']),
            'image': 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
            'description': 'The iconic Pink City celebrated for formidable hilltop forts, ornate royal palaces, astronomy observatories, and block-print handicrafts.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 4,
            'latitude': 26.9124,
            'longitude': 75.7873,
        },
        {
            'id': 'mumbai',
            'name': 'Mumbai',
            'type': 'Financial & Coastal Megacity',
            'state': 'Maharashtra',
            'state_id': 'maharashtra',
            'region': 'West India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Beaches', 'Food & Culture']),
            'image': 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
            'description': 'The energetic financial capital on the Arabian Sea, renowned for colonial landmarks, street delicacies, and Marine Drive sunsets.',
            'safety_level': 'SAFE',
            'best_season': 'November to February',
            'place_count': 3,
            'latitude': 18.9220,
            'longitude': 72.8347,
        },
        {
            'id': 'goa',
            'name': 'Goa',
            'type': 'Coastal Paradise & Portuguese Heritage',
            'state': 'Goa',
            'state_id': 'goa',
            'region': 'West India',
            'country': 'India',
            'categories': json.dumps(['Beaches', 'Heritage', 'Nature']),
            'image': 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
            'description': 'Tropical coastal haven celebrated for golden beaches, UNESCO Latin quarters, water sports, and spice plantations.',
            'safety_level': 'SAFE',
            'best_season': 'November to March',
            'place_count': 3,
            'latitude': 15.2993,
            'longitude': 74.1240,
        },
        {
            'id': 'agra',
            'name': 'Agra',
            'type': 'Mughal Imperial Heritage',
            'state': 'Uttar Pradesh',
            'state_id': 'uttar-pradesh',
            'region': 'North India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Art & Architecture']),
            'image': 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
            'description': 'Home to the immortal Taj Mahal on the Yamuna riverbank, majestic red sandstone forts, and exquisite marble inlay artistry.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 2,
            'latitude': 27.1767,
            'longitude': 78.0081,
        },
        {
            'id': 'varanasi',
            'name': 'Varanasi',
            'type': 'Spiritual & Cultural Heritage Capital',
            'state': 'Uttar Pradesh',
            'state_id': 'uttar-pradesh',
            'region': 'North India',
            'country': 'India',
            'categories': json.dumps(['Spiritual', 'Heritage', 'Food & Culture']),
            'image': 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
            'description': 'Ancient living city on the sacred Ganga, revered for evening Ganga Aarti ceremonies, silk weaving, and spiritual ghats.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 2,
            'latitude': 25.3176,
            'longitude': 82.9739,
        },
        {
            'id': 'manali',
            'name': 'Manali',
            'type': 'Himalayan Mountain Retreat',
            'state': 'Himachal Pradesh',
            'state_id': 'himachal-pradesh',
            'region': 'North India',
            'country': 'India',
            'categories': json.dumps(['Nature', 'Adventure', 'Hill Station']),
            'image': 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
            'description': 'Alpine paradise nestled in the Beas River valley featuring snow-capped peaks, pine forests, and adventure sports.',
            'safety_level': 'SAFE',
            'best_season': 'October to June',
            'place_count': 2,
            'latitude': 32.2432,
            'longitude': 77.1892,
        },
        {
            'id': 'kochi',
            'name': 'Kochi',
            'type': 'Coastal Port & Spice Capital',
            'state': 'Kerala',
            'state_id': 'kerala',
            'region': 'South India',
            'country': 'India',
            'categories': json.dumps(['Heritage', 'Food & Culture', 'Nature']),
            'image': 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
            'description': 'Queen of the Arabian Sea boasting Chinese fishing nets, historic Jew Town synagogues, and backwater lagoons.',
            'safety_level': 'SAFE',
            'best_season': 'October to March',
            'place_count': 2,
            'latitude': 9.9312,
            'longitude': 76.2673,
        },
    ]

    for d in destinations_data:
        db.session.add(Destination(**d))

    # 3. Tourist Places Dataset
    places_data = [
        # Hyderabad
        {
            'id': 'charminar',
            'destination_id': 'hyderabad',
            'destination_name': 'Hyderabad',
            'name': 'Charminar & Laad Bazaar',
            'state': 'Telangana',
            'region': 'South India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=800&q=80',
            'description': 'Iconic 1591 CE four-minaret monument standing at the historic core of old Hyderabad, surrounded by lacquer bangle and pearl markets.',
            'best_time': '4:00 PM - 8:30 PM',
            'duration': '2 Hours',
            'crowd_level': 'High',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Four 48.7m minarets', 'Old city upper balcony', '400-year-old clock']),
            'things_to_do': json.dumps(['Climb spiral staircase', 'Shop in Laad Bazaar', 'Irani Chai at Nimrah Cafe']),
            'nearby_attractions': json.dumps(['Mecca Masjid', 'Chowmahalla Palace', 'Salar Jung Museum']),
            'nearby_safe_zones': json.dumps(['Charminar Police Station (150m)', 'Osmania Hospital (800m)', 'Tourist Help Desk (200m)']),
            'latitude': 17.3616,
            'longitude': 78.4747,
        },
        {
            'id': 'golconda-fort',
            'destination_id': 'hyderabad',
            'destination_name': 'Hyderabad',
            'name': 'Golconda Fort & Citadel',
            'state': 'Telangana',
            'region': 'South India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?auto=format&fit=crop&w=800&q=80',
            'description': 'Monumental medieval fortress complex renowned for miraculous acoustic engineering, Koh-i-Noor diamond vaults, and hilltop citadel vistas.',
            'best_time': '3:30 PM - 6:30 PM',
            'duration': '3 Hours',
            'crowd_level': 'Moderate',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Fateh Darwaza clapping acoustic arch', 'Baradari hilltop pavilion', 'Qutb Shahi royal arms vaults']),
            'things_to_do': json.dumps(['Test clapping sound echo', 'Hike to the highest bastion', 'Attend Evening Sound & Light show']),
            'nearby_attractions': json.dumps(['Qutb Shahi Tombs', 'Taramati Baradari']),
            'nearby_safe_zones': json.dumps(['Golconda Police Station (300m)', 'Fort Security Command Post']),
            'latitude': 17.3833,
            'longitude': 78.4011,
        },
        {
            'id': 'hussain-sagar',
            'destination_id': 'hyderabad',
            'destination_name': 'Hyderabad',
            'name': 'Hussain Sagar & Buddha Statue',
            'state': 'Telangana',
            'region': 'South India',
            'category': 'Nature',
            'image': 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
            'description': 'Heart-shaped historic lake featuring a monolithic 18-meter white granite Buddha statue on Gibraltar Rock and waterfront promenade parks.',
            'best_time': '5:00 PM - 9:00 PM',
            'duration': '2 Hours',
            'crowd_level': 'Moderate',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['18m monolithic Buddha', 'Necklace Road promenade', 'Lumbini musical fountain']),
            'things_to_do': json.dumps(['Speedboat ride to Gibraltar Rock', 'Evening walk on Tank Bund', 'Laser show at Lumbini Park']),
            'nearby_attractions': json.dumps(['Birla Mandir', 'NTR Gardens', 'Sanjeevaiah Park']),
            'nearby_safe_zones': json.dumps(['Lake Police Station (200m)', 'Lumbini Park Security Center']),
            'latitude': 17.4239,
            'longitude': 78.4738,
        },
        {
            'id': 'birla-mandir-hyd',
            'destination_id': 'hyderabad',
            'destination_name': 'Hyderabad',
            'name': 'Birla Mandir',
            'state': 'Telangana',
            'region': 'South India',
            'category': 'Spiritual',
            'image': 'https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=800&q=80',
            'description': 'Magnificent white Rajasthani marble temple perched atop the 280-foot Naubat Pahad hill overlooking Hussain Sagar lake.',
            'best_time': '6:00 AM - 11:30 AM, 4:00 PM - 8:30 PM',
            'duration': '1.5 Hours',
            'crowd_level': 'Low',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Intricate marble carvings', 'Panoramic city & lake views', 'Ornate sanctum sanctorum']),
            'things_to_do': json.dumps(['Meditation in quiet prayer hall', 'Evening sunset photography of lake']),
            'nearby_attractions': json.dumps(['Hussain Sagar', 'BM Birla Science Centre']),
            'nearby_safe_zones': json.dumps(['Saifabad Police Station (400m)', 'Birla Temple Security Desk']),
            'latitude': 17.4062,
            'longitude': 78.4691,
        },

        # Visakhapatnam
        {
            'id': 'rishikonda-beach',
            'destination_id': 'visakhapatnam',
            'destination_name': 'Visakhapatnam',
            'name': 'Rishikonda Blue Flag Beach',
            'state': 'Andhra Pradesh',
            'region': 'South India',
            'category': 'Beaches',
            'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
            'description': 'Eco-certified Blue Flag beach nestled between rocky green headlands, renowned for water sports, surfing schools, and golden sands.',
            'best_time': '6:00 AM - 10:00 AM, 4:00 PM - 7:00 PM',
            'duration': '3 Hours',
            'crowd_level': 'Moderate',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Blue Flag eco-boardwalk', 'Surfing zone', 'Rocky headlands']),
            'things_to_do': json.dumps(['Speed boating & jet skiing', 'Surfing lessons', 'Coastal seafood snacking']),
            'nearby_attractions': json.dumps(['Kailasagiri', 'Thotlakonda Buddhist Complex', 'INS Kursura']),
            'nearby_safe_zones': json.dumps(['Rishikonda Lifeguard & Police Post (50m)', 'Coastal Marine Police Station']),
            'latitude': 17.7828,
            'longitude': 83.3854,
        },
        {
            'id': 'kailasagiri',
            'destination_id': 'visakhapatnam',
            'destination_name': 'Visakhapatnam',
            'name': 'Kailasagiri Hilltop Park & Ropeway',
            'state': 'Andhra Pradesh',
            'region': 'South India',
            'category': 'Nature',
            'image': 'https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=800&q=80',
            'description': 'Lush hilltop park perched 360 feet above the Bay of Bengal, featuring mammoth white Shiva-Parvati statues and circular toy train rides.',
            'best_time': '3:30 PM - 7:30 PM',
            'duration': '2.5 Hours',
            'crowd_level': 'Moderate',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['40-foot Shiva Parvati statue', 'Titanic viewpoint', 'Floral clock']),
            'things_to_do': json.dumps(['Scenic cable car ropeway ride', 'Toy train panoramic ride', 'Sunset view of coast']),
            'nearby_attractions': json.dumps(['Rishikonda Beach', 'Tenneti Park', 'INS Kursura']),
            'nearby_safe_zones': json.dumps(['Kailasagiri Security Command Post', 'MVP Colony Police Outpost (1.2km)']),
            'latitude': 17.7490,
            'longitude': 83.3422,
        },
        {
            'id': 'borra-caves',
            'destination_id': 'visakhapatnam',
            'destination_name': 'Visakhapatnam',
            'name': 'Borra Caves & Ananthagiri Hills',
            'state': 'Andhra Pradesh',
            'region': 'South India',
            'category': 'Nature',
            'image': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
            'description': 'Million-year-old deep karst limestone caves featuring speleothem stalactites, stalagmites, and illuminated subterranean chambers.',
            'best_time': '10:00 AM - 4:00 PM',
            'duration': '3 Hours',
            'crowd_level': 'Low',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Natural Shiva lingam stalagmite', 'Multi-colored LED illuminated karst', 'Gosthani river gorge']),
            'things_to_do': json.dumps(['Subterranean exploration', 'Taste bamboo chicken in Araku', 'Photography']),
            'nearby_attractions': json.dumps(['Araku Valley', 'Katiki Waterfalls', 'Coffee Plantations']),
            'nearby_safe_zones': json.dumps(['Borra Caves Tourism Guard Post', 'Ananthagiri Medical Dispensary']),
            'latitude': 18.2804,
            'longitude': 83.0398,
        },

        # Delhi
        {
            'id': 'red-fort',
            'destination_id': 'delhi',
            'destination_name': 'Delhi',
            'name': 'Red Fort (Lal Qila)',
            'state': 'Delhi',
            'region': 'North India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
            'description': 'UNESCO World Heritage red sandstone Mughal fortress complex constructed by Emperor Shah Jahan in 1639.',
            'best_time': '9:30 AM - 4:30 PM',
            'duration': '2.5 Hours',
            'crowd_level': 'High',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Lahori Gate', 'Diwan-i-Aam & Diwan-i-Khas', 'Moti Masjid']),
            'things_to_do': json.dumps(['Explore royal museum galleries', 'Sound & light evening show']),
            'nearby_attractions': json.dumps(['Chandni Chowk', 'Jama Masjid', 'Raj Ghat']),
            'nearby_safe_zones': json.dumps(['Kotwali Police Station (200m)', 'Red Fort Security Command Hub']),
            'latitude': 28.6562,
            'longitude': 77.2410,
        },

        # Jaipur
        {
            'id': 'amber-fort',
            'destination_id': 'jaipur',
            'destination_name': 'Jaipur',
            'name': 'Amber Palace & Fort',
            'state': 'Rajasthan',
            'region': 'North India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
            'description': 'Grand UNESCO World Heritage hilltop fortress overlooking Maota Lake, famous for Sheesh Mahal mirror palace and Rajput architecture.',
            'best_time': '8:30 AM - 5:30 PM',
            'duration': '3 Hours',
            'crowd_level': 'High',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Sheesh Mahal (Mirror Palace)', 'Ganesh Pol entrance', 'Maota Lake garden view']),
            'things_to_do': json.dumps(['Walk through subterranean tunnels', 'Evening heritage illumination']),
            'nearby_attractions': json.dumps(['Jaigarh Fort', 'Nahargarh Fort', 'Jal Mahal']),
            'nearby_safe_zones': json.dumps(['Amber Police Station (200m)', 'Rajasthan Tourist Assistance Booth']),
            'latitude': 26.9855,
            'longitude': 75.8513,
        },
        {
            'id': 'hawa-mahal',
            'destination_id': 'jaipur',
            'destination_name': 'Jaipur',
            'name': 'Hawa Mahal (Palace of Winds)',
            'state': 'Rajasthan',
            'region': 'North India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
            'description': 'Five-story pink and red sandstone palace featuring 953 honeycomb jharokhas (casements) designed for cool ventilation and royal observation.',
            'best_time': '9:00 AM - 4:30 PM',
            'duration': '1.5 Hours',
            'crowd_level': 'Moderate',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['953 carved jharokha windows', 'Ratan Mandir stained glass', 'Top terrace view of Jantar Mantar']),
            'things_to_do': json.dumps(['Rooftop cafe photography', 'Explore Johari Bazaar for gemstones']),
            'nearby_attractions': json.dumps(['City Palace', 'Jantar Mantar', 'Bapu Bazaar']),
            'nearby_safe_zones': json.dumps(['Manak Chowk Police Station (100m)', 'Jaipur Tourist Police Outpost']),
            'latitude': 26.9239,
            'longitude': 75.8267,
        },

        # Agra
        {
            'id': 'taj-mahal',
            'destination_id': 'agra',
            'destination_name': 'Agra',
            'name': 'Taj Mahal',
            'state': 'Uttar Pradesh',
            'region': 'North India',
            'category': 'Heritage',
            'image': 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
            'description': 'Universal masterpiece of ivory-white marble architecture built by Shah Jahan in memory of Mumtaz Mahal, set in formal charbagh gardens.',
            'best_time': 'Sunrise (6:00 AM - 8:30 AM)',
            'duration': '3 Hours',
            'crowd_level': 'High',
            'safety_level': 'SAFE',
            'things_to_see': json.dumps(['Central white marble dome & minarets', 'Pietra dura semi-precious stone inlay', 'Yamuna river reflection']),
            'things_to_do': json.dumps(['Sunrise walk in charbagh gardens', 'Explore Taj Museum']),
            'nearby_attractions': json.dumps(['Agra Fort', 'Mehtab Bagh', 'Itmad-ud-Daulah']),
            'nearby_safe_zones': json.dumps(['Taj Mahal Tourist Police Station (50m)', 'CISF Central Security Command Post']),
            'latitude': 27.1751,
            'longitude': 78.0421,
        },
    ]

    for p in places_data:
        db.session.add(TouristPlace(**p))

    # 4. Verified Services Dataset (24/7 Police, Helplines, Hospitals)
    services_data = [
        # Hyderabad
        {
            'destination_id': 'hyderabad',
            'service_type': 'POLICE',
            'name': 'Telangana Tourist Police Command Outpost',
            'contact_number': '112 / 040-27852435',
            'address': 'Near Charminar Plaza & Tank Bund, Hyderabad',
            'latitude': 17.3620,
            'longitude': 78.4750,
            'is_24_7': True,
        },
        {
            'destination_id': 'hyderabad',
            'service_type': 'HOSPITAL',
            'name': 'Osmania General Hospital Emergency Ward',
            'contact_number': '040-24600121',
            'address': 'Afzal Gunj, High Court Road, Hyderabad',
            'latitude': 17.3750,
            'longitude': 78.4780,
            'is_24_7': True,
        },
        {
            'destination_id': 'hyderabad',
            'service_type': 'TOURIST_DESK',
            'name': 'Telangana Tourism 24/7 Information Center',
            'contact_number': '1363 / 040-23450165',
            'address': 'Kala Bhavan, Ravindra Bharathi, Hyderabad',
            'latitude': 17.4020,
            'longitude': 78.4710,
            'is_24_7': True,
        },

        # Visakhapatnam
        {
            'destination_id': 'visakhapatnam',
            'service_type': 'POLICE',
            'name': 'Andhra Pradesh Coastal Marine & Tourist Police',
            'contact_number': '112 / 0891-2565454',
            'address': 'Beach Road, Near RK Beach, Visakhapatnam',
            'latitude': 17.7120,
            'longitude': 83.3240,
            'is_24_7': True,
        },
        {
            'destination_id': 'visakhapatnam',
            'service_type': 'HOSPITAL',
            'name': 'King George Hospital (KGH) Trauma Center',
            'contact_number': '0891-2564891',
            'address': 'Collector Office Road, Maharanipeta, Visakhapatnam',
            'latitude': 17.7050,
            'longitude': 83.3080,
            'is_24_7': True,
        },

        # Delhi
        {
            'destination_id': 'delhi',
            'service_type': 'POLICE',
            'name': 'Delhi Tourist Police Dedicated Unit',
            'contact_number': '112 / 011-23363363',
            'address': 'Pahar Ganj & Connaught Place, New Delhi',
            'latitude': 28.6315,
            'longitude': 77.2167,
            'is_24_7': True,
        },

        # Jaipur
        {
            'destination_id': 'jaipur',
            'service_type': 'POLICE',
            'name': 'Rajasthan Tourist Assistance Force (TAF)',
            'contact_number': '112 / 0141-2374824',
            'address': 'Near Hawa Mahal & Amber Fort, Jaipur',
            'latitude': 26.9240,
            'longitude': 75.8270,
            'is_24_7': True,
        },
    ]

    for s in services_data:
        db.session.add(VerifiedService(**s))

    # 5. Sample Initial Incident Reports for Admin Triage
    sample_reports = [
        {
            'client_action_id': 'seed_report_001',
            'place_id': 'charminar',
            'destination_id': 'hyderabad',
            'report_type': 'crowd_surge',
            'severity': 'HIGH',
            'status': 'PENDING',
            'description': 'Heavy congestion and bottleneck near Laad Bazaar eastern entrance. Recommend tourist police patrol redirection.',
            'reported_by': 'Tourist Patrol Volunteer',
            'latitude': 17.3616,
            'longitude': 78.4747,
        },
        {
            'client_action_id': 'seed_report_002',
            'place_id': 'rishikonda-beach',
            'destination_id': 'visakhapatnam',
            'report_type': 'safety_alert',
            'severity': 'MEDIUM',
            'status': 'REVIEWING',
            'description': 'High tidal wave warning along the north rocky headland. Lifeguard red flags deployed.',
            'reported_by': 'Coastal Lifeguard Unit',
            'latitude': 17.7828,
            'longitude': 83.3854,
        },
        {
            'client_action_id': 'seed_report_003',
            'place_id': 'amber-fort',
            'destination_id': 'jaipur',
            'report_type': 'infrastructure_issue',
            'severity': 'LOW',
            'status': 'IN_PROGRESS',
            'description': 'Cobblestone path maintenance underway near Suraj Pol gate. Alternative pedestrian ramp open.',
            'reported_by': 'ASI Heritage Desk',
            'latitude': 26.9855,
            'longitude': 75.8513,
        },
        {
            'client_action_id': 'seed_report_004',
            'place_id': 'red-fort',
            'destination_id': 'delhi',
            'report_type': 'safety_alert',
            'severity': 'CRITICAL',
            'status': 'RESOLVED',
            'description': 'Medical assist requested for dehydrated elderly traveler. Resolved: First aid administered at Red Fort medical booth.',
            'reported_by': 'Traveler Assist Helpline',
            'latitude': 28.6562,
            'longitude': 77.2410,
        },
    ]

    for r in sample_reports:
        db.session.add(Report(**r))

    db.session.commit()
    print('[MockDataService] Database populated with destinations, tourist places, verified services, and triage reports.')
