import { TOURIST_PLACES } from "../../data/touristPlaces";
import { DESTINATIONS } from "../../data/destinations";

/**
 * Landmark Recognition Simulation — No camera / computer-vision API required.
 * Simulates a recognition scan using the local tourist place dataset.
 */

/** Generate a deterministic-ish confidence between 82–97% */
function simulateConfidence(seed = 0) {
  return 82 + ((seed * 17) % 16);
}

/**
 * Simulate landmark recognition given a user-selected category / name hint.
 * @param {Object} opts
 * @param {string} [opts.category]   - category filter hint
 * @param {string} [opts.nameHint]   - partial name or keyword
 * @param {string} [opts.destinationId] - restrict to a destination
 * @returns {Promise<LandmarkResult>}
 */
export async function recognizeLandmark({ category, nameHint, destinationId } = {}) {
  // Simulate processing delay
  await new Promise((r) => setTimeout(r, 1200));

  let pool = [...TOURIST_PLACES];
  if (destinationId) pool = pool.filter((p) => p.destinationId === destinationId);
  if (category && category !== "ALL") pool = pool.filter((p) => p.category === category);
  if (nameHint) {
    const hint = nameHint.toLowerCase();
    const filtered = pool.filter((p) => p.name.toLowerCase().includes(hint) || p.description.toLowerCase().includes(hint));
    if (filtered.length > 0) pool = filtered;
  }

  if (pool.length === 0) {
    return { success: false, message: "No matching landmark found in dataset." };
  }

  // Pick deterministically based on name length (stable across calls for same hint)
  const idx = pool.length > 1 ? Math.floor(pool.length / 2) : 0;
  const place = pool[idx];
  const dest = DESTINATIONS.find((d) => d.id === place.destinationId);
  const confidence = simulateConfidence(place.name.length + place.category.length);

  return {
    success: true,
    place,
    destination: dest || null,
    confidence,
    estimatedDistanceKm: parseFloat((0.5 + Math.random() * 3).toFixed(1)),
    crowdLevel: place.crowdLevel,
    safetyLevel: place.safetyLevel,
    category: place.category,
    sourceLabel: "AI Estimate — Prototype Vision Simulation",
    note: "This result is generated by a rule-based simulation, not a real computer vision model.",
  };
}

/** Return all categories for the landmark scanner selector */
export function getLandmarkCategories() {
  const cats = [...new Set(TOURIST_PLACES.map((p) => p.category))];
  return ["ALL", ...cats.sort()];
}
